---
- name: Prep learner machines
  hosts: all
  remote_user: centos
  become: true
  tasks:
  - name: Enable password-based authentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication.*no'
      line: PasswordAuthentication=yes
  - name: Restart sshd
    service:
      name: sshd
      state: restarted
  - name: Set centos user password
    user:
      name: centos
      password: "{{ newpassword|password_hash('sha512') }}"
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Break httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80'
      line: Listen to the music
  - name: Stop httpd
    service:
      name: httpd
      state: stopped