---
- name: Prep learner machines
  hosts: all
  remote_user: centos
  become: true
  tasks:
  - name: Disable SELinux
    selinux:
      policy: targeted
      state: permissive
  - name: Enable password-based authentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication.*no'
      line: PasswordAuthentication=yes
  - name: Change to port 2000
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Port 22'
      line: Port 2000
  - name: Set centos user password
    user:
      name: centos
      password: "{{ newpassword|password_hash('sha512') }}"
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Break httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80'
      line: "Listen 8000 \n# Fire me huh. See how you handle this"
  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
      owner: apache
      group: apache
    with_items:
      - /var/www/website
      - /var/www/website.old
      - /var/www/website.old/about
      - /var/www/website.old/about/our-ceo
      - /var/www/website.old/terms-and-conditions
  - name: Deploy html files
    copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      owner: apache
      group: apache
      mode: 0755
    with_items:
      - content: |
          <html>
            <head>
              <title>Our Website</title>
            </head>
            <body>
              <h1>Welcome to our website!</h1>
              <ul>
                <li><a href="/about">Our about page</a></li>
                <li><a href="/terms-and-conditions">Terms and conditions</a></li>
              <ul>
            </body>
          </html>
        dest: /var/www/website.old/index.html
      - content: |
          <html>
            <head>
              <title>About us</title>
            </head>
            <body>
              <h1>About us</h1>
              <p>We must write something here before the website goes live..</p>
              <br>
              <a href="/about/our-ceo">Our CEO</a>
            </body>
          </html>
        dest: /var/www/website.old/about/index.html
      - content: |
          <html>
            <head>
              <title>Our CEO</title>
            </head>
            <body>
              <h1>Our CEO</h1>
              <p>So basically, our CEO is awesome. Look at this website he commissioned!</p>
            </body>
          <html>
        dest: /var/www/website.old/about/our-ceo/index.html
      - content: |
          <html>
            <head>
              <title>Terms and Conditions</title>
            </head>
            <body>
              <h1>Terms and Conditions</h1>
              <p>Please be nice to us.. we're new here.</p>
            </body>
          <html>
        dest: /var/www/website.old/terms-and-conditions/index.html
      - content: |
          <html>
            <head>
              <title>These guys SUCK</title>
            </head>
            <body>
              <h1>Fired!</h1>
              <p>Fired just for turning up to work drunk. Rude!</p>
            </body>
          <html>
        dest: /var/www/website/index.html
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
  - name: Restart sshd
    service:
      name: sshd
      state: restarted
